[tool.ruff]
line-length = 100
target-version = "py311"

[tool.ruff.lint]
select = ["E", "W", "F", "I", "B", "C4", "SIM", "UP", "TCH"]
ignore = []

[tool.ruff.lint.isort]
known-first-party = ["imre", "wfm_core", "shifts"]